apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartcoop-os.fullname" . }}-rabbitmq-credentials
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}